name: Atividade 2 - MPI Reduce

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test-mpi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich

      - name: Listar arquivos do repositório
        run: |
          find .

      - name: Compilar programa
        run: |
          mpicc atividade2.c -o atividade2

      - name: Executar programa
        run: |
          mpirun -np 4 ./atividade2 1000
